### ISSUE TITLE
Details on datasets used in the competition? 

### ISSUE THREAD

**Issue by vedant-sanil** [cxxz/automl_decathlon_starter_kit#2]
Hi, 

Could we have some details on the 10 datasets being used in the competition? Specifically on the modalities of these datasets, and any potential public links to them?

**Comment by nick11roberts** [comment]
Hi Vedant! Unfortunately we do not plan to release additional information about these datasets. In general, since we will be evaluating all of the methods on a set of 10 new tasks, we don’t believe that additional information would help anyway since it may result in overfitting your methods to the dev tasks. 

With that said, please feel free to make use of any of the metadata that we have provided in the downloads for these datasets, as similar information will also be included with the test datasets.
